//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/zm_dust_world.html
halflife.wad
decals.wad
cs_cbble.wad
cs_assault.wad
cs_bdog.wad
models/zm_dust_world/re_deadguy_1.mdl
models/zm_dust_world/re_deadguy_2.mdl
models/zm_dust_world/re_deadguy_3.mdl
models/zm_dust_world/fan_ceiling-attach.mdl
models/zm_dust_world/25_6a6o4ka-napxaet.mdl
models/zm_dust_world/bush.mdl
models/zm_dust_world/tuscan_grass1a.mdl
models/zm_dust_world/tv_plasma.mdl
models/zm_dust_world/vending_machine.mdl
cs_dust.wad
maps/zm_dust_world.bsp
maps/zm_dust_world.txt
